# Generated by Django 5.1.2 on 2024-10-15 23:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro_produtos', '0003_delete_product_remove_produto_descricao_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='produto',
            old_name='qtd_estoque',
            new_name='quantidade_em_estoque',
        ),
    ]
